//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSuper4U
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemBasket
    {
        public int ItemBasketId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> BasketId { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Basket Basket { get; set; }
        public virtual Item Item { get; set; }
    }
}
